// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXzqQrSh3TqxUnslZ6AESovavmK9kbnFc',
    appId: '1:814889837143:web:939e2b869aedcf2139b912',
    messagingSenderId: '814889837143',
    projectId: 'flutter-chat-app-8a444',
    authDomain: 'flutter-chat-app-8a444.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8a444.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIOnO0O1UV6ZNofs1LCcdYKFwDSenvdvE',
    appId: '1:814889837143:android:5b1572578ca9f51039b912',
    messagingSenderId: '814889837143',
    projectId: 'flutter-chat-app-8a444',
    storageBucket: 'flutter-chat-app-8a444.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu23hydpd4ZuLSxkUgy-cli7kxf1-2BzU',
    appId: '1:814889837143:ios:747b3787746d48c639b912',
    messagingSenderId: '814889837143',
    projectId: 'flutter-chat-app-8a444',
    storageBucket: 'flutter-chat-app-8a444.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );
}
